### ISSUE TITLE
standard_init_linux.go:230: exec user process caused: permission denied

### ISSUE THREAD

**Issue by man9r0ve** [yellowgg2/youngs-ytdl#9]
안녕하세요.

처음으로 git clone 해서 내려 받은 후 `.env` 파일 수정 후 빌드 했는데 `ytdl-service` 에서 아래와 같은 에러가 발생합니다.

그리고 혹시 자막 파일은 다운로드 기능이 있을까요?

```bash
standard_init_linux.go:230: exec user process caused: permission denied
```

아마 `ytdl-service` 실행 시 권한 에러가 발생하는데 어떻게 하면 될까요??

### docker-compose.yml 파일 내용
```yml
version: "3.1"

services:
  ytdl-download-bot:
    container_name: ytdl-download-bot
    image: ytdl-bot
    build:
      context: ./bot
      args:
        PUID: $PUID
        PGID: $PGID
        UNAME: $UNAME
    restart: always
    environment:
      - BOT_API_TOKEN=$TELEGRAM_BOT_API_TOKEN
      - ADMIN_USERNAME=$TELEGRAM_ADMIN_USERNAME
      - ADMIN_DESC=$TELEGRAM_ADMIN_DESC
      - ADMIN_CHATID=$TELEGRAM_ADMIN_CHATID
      - BOT_LANG=$BOT_LANG
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOWNLOAD_PATH:/ytdlbot/download
      - $DATABASE_PATH:/ytdlbot/db
  ytdl-service:
    container_name: ytdl-service
    image: ytdl-service
    build:
      context: ./ydls
    restart: always
```

### .env 파일 내용
```
TELEGRAM_BOT_API_TOKEN=1234:토큰
TELEGRAM_ADMIN_USERNAME=username
TELEGRAM_ADMIN_DESC="관리자"
TELEGRAM_ADMIN_CHATID=챗아이디
DOWNLOAD_PATH=./youtube-dl/bot
DATABASE_PATH=./youtube-dl/bot/db
BOT_LANG=ko
PUID=1026
PGID=100
UNAME=taken
```
